 DROP TABLE IF EXISTS ODONTOLOGOS;

CREATE TABLE ODONTOLOGOS (ID INT AUTO_INCREMENT PRIMARY KEY, MATRICULA INT,
NOMBRE VARCHAR(100),
APELLIDO VARCHAR(100));

INSERT INTO ODONTOLOGOS (MATRICULA,NOMBRE,APELLIDO) VALUES (123,'Yudi','Morales');
INSERT INTO ODONTOLOGOS (MATRICULA,NOMBRE,APELLIDO) VALUES (678,'Angel','Cuellar');
INSERT INTO ODONTOLOGOS (MATRICULA,NOMBRE,APELLIDO) VALUES (985,'Eliza','Guzman');