#!/bin/bash
for word in $(cat lista_nombres)
do
  echo"El nombre es $word"
done


if[ $word = "juan" ]; then
       echo "Encontre a $word"
else
       let a = $a+1
fi



juan
maria
elena
yudi
yuli
daniela
marcela 
carmen
fede
silvina
marcos
andrea
